[project]
name = "ecommercehelper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent-client-protocol==0.10.0",
    "aiosqlite==0.22.1",
    "annotated-doc==0.0.4",
    "beautifulsoup4==4.14.3",
    "blockbuster==1.5.26",
    "cloudpickle==3.1.2",
    "croniter==6.2.2",
    "deepagents==0.5.9",
    "deepagents-acp==0.0.6",
    "deepagents-cli==0.0.57",
    "dotenv>=0.9.9",
    "fastapi==0.135.3",
    "forbiddenfruit==0.1.4",
    "googleapis-common-protos==1.74.0",
    "grpcio==1.80.0",
    "grpcio-health-checking==1.80.0",
    "grpcio-tools==1.80.0",
    "httpx-sse==0.4.3",
    "importlib-metadata==8.7.1",
    "ipython>=9.17.1",
    "jsonschema-rs==0.44.1",
    "langchain>=1.4.0",
    "langchain-mcp-adapters==0.2.2",
    "langchain-ollama==1.1.0",
    "langchain-openai>=1.6.2",
    "langgraph-api==0.10.0",
    "langgraph-checkpoint-sqlite==3.1.0",
    "langgraph-cli==0.4.30",
    "langgraph-runtime-inmem==0.30.0",
    "linkify-it-py==2.1.0",
    "markdown-it-py==4.2.0",
    "markdownify==1.2.2",
    "mcp==1.27.0",
    "mdit-py-plugins==0.6.0",
    "mdurl==0.1.2",
    "ollama==0.6.1",
    "opentelemetry-api==1.40.0",
    "opentelemetry-exporter-otlp-proto-common==1.40.0",
    "opentelemetry-exporter-otlp-proto-http==1.40.0",
    "opentelemetry-proto==1.40.0",
    "opentelemetry-sdk==1.40.0",
    "opentelemetry-semantic-conventions==0.61b0",
    "pandas>=3.0.5",
    "pathspec==1.0.4",
    "platformdirs==4.9.6",
    "pydantic-settings==2.14.2",
    "pyjwt==2.13.0",
    "pyperclip==1.11.0",
    "pytest>=9.1.1",
    "pywin32==311",
    "rich==15.0.0",
    "setuptools==82.0.1",
    "soupsieve==2.8.4",
    "sqlite-vec==0.1.9",
    "sse-starlette==3.3.4",
    "streamlit>=1.63.0",
    "structlog==25.5.0",
    "tavily-python==0.7.24",
    "textual==8.2.5",
    "textual-autocomplete==4.0.6",
    "textual-speedups==0.2.1",
    "tomli-w==1.2.0",
    "tqdm==4.67.3",
    "uc-micro-py==2.0.0",
    "watchfiles==1.1.1",
    "zipp==3.23.0",
]
