[project]
name = "ecommercehelper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepagents>=0.7.13",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.2",
    "openai>=3.11.0",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
]
