from dataclasses import dataclass
import json
import os
import sqlite3

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.tools import ToolRuntime, tool
from langchain_openai import ChatOpenAI

load_dotenv()

DB_NAME = os.getenv("ECOMMERCE_DB_PATH", "ecommerce.db")

llm = ChatOpenAI(
    model="gpt-5-nano",
    temperature=0,
)

# Runtime context

@dataclass
class InsightContext:
    """
    Immutable information about the user making the request.

    This is passed by the application/orchestrator rather than
    generated by the LLM.
    """

    user_role: str

# Helpers

def _normalize_role(role: str) -> str:
    return role.strip().lower()


def _manager_authorized(role: str) -> bool:
    """
    Roles allowed to access protected business analytics.

    'owner' and 'admin' are accepted as manager-equivalent roles
    so the Insights Agent can remain compatible with the project's
    existing Owner terminology.
    """

    return _normalize_role(role) in {
        "manager",
        "owner",
        "admin",
    }


def _item_variants(item: str) -> tuple[str, str]:
    """
    Provide a very small normalization layer for singular/plural
    inventory entries.

    Example:
        apple  -> ("apple", "apples")
        apples -> ("apple", "apples")

    This is intentionally simple for the MVP.
    """

    normalized = item.strip().lower()

    if normalized.endswith("s"):
        singular = normalized[:-1]
        plural = normalized
    else:
        singular = normalized
        plural = f"{normalized}s"

    return singular, plural


# Insight tools

@tool
def get_inventory_count(item: str) -> str:
    """
    Get the total current inventory count for a product.

    Use this tool for questions such as:
    - How many apples are there?
    - How many keyboards are in stock?
    - What is the current quantity of an item?

    Inventory counts are not treated as protected historical
    business analytics.
    """

    singular, plural = _item_variants(item)

    try:
        with sqlite3.connect(DB_NAME) as conn:
            cursor = conn.cursor()

            cursor.execute(
                """
                SELECT COALESCE(SUM(count), 0)
                FROM inventory
                WHERE LOWER(TRIM(item)) IN (?, ?)
                """,
                (singular, plural),
            )

            total = cursor.fetchone()[0]

        return json.dumps(
            {
                "item": item,
                "count": int(total),
            }
        )

    except sqlite3.Error as exc:
        return json.dumps(
            {
                "error": "database_error",
                "message": str(exc),
            }
        )


@tool
def get_sales_history(
    runtime: ToolRuntime[InsightContext],
    item: str = "",
) -> str:
    """
    Retrieve historical sales information.

    This tool contains protected business information and may only
    be used by an authorized manager, owner, or administrator.

    Optionally provide an item name to restrict the sales history
    to one product.
    """

    role = runtime.context.user_role

    # Deterministic authorization boundary.
    # The LLM cant override this check.
    if not _manager_authorized(role):
        return json.dumps(
            {
                "authorized": False,
                "error": "not_authorized",
                "message": (
                    "You are not authorized to access historical "
                    "sales information."
                ),
            }
        )

    try:
        with sqlite3.connect(DB_NAME) as conn:
            cursor = conn.cursor()

            if item.strip():
                singular, plural = _item_variants(item)

                cursor.execute(
                    """
                    SELECT
                        date,
                        item,
                        SUM(count) AS units_sold,
                        SUM(total_price) AS revenue
                    FROM sales
                    WHERE LOWER(TRIM(item)) IN (?, ?)
                    GROUP BY date, item
                    ORDER BY date ASC
                    """,
                    (singular, plural),
                )

            else:
                cursor.execute(
                    """
                    SELECT
                        date,
                        item,
                        SUM(count) AS units_sold,
                        SUM(total_price) AS revenue
                    FROM sales
                    GROUP BY date, item
                    ORDER BY date ASC, item ASC
                    """
                )

            rows = cursor.fetchall()

        sales = [
            {
                "date": row[0],
                "item": row[1],
                "units_sold": row[2],
                "revenue": row[3],
            }
            for row in rows
        ]

        return json.dumps(
            {
                "authorized": True,
                "records": sales,
                "record_count": len(sales),
            }
        )

    except sqlite3.Error as exc:
        return json.dumps(
            {
                "authorized": True,
                "error": "database_error",
                "message": str(exc),
            }
        )


# Insights Agent

llm = ChatOpenAI(
    model="gpt-5-nano",
    temperature=0,
)


INSIGHT_SYSTEM_PROMPT = """
You are the Business Insights Agent for EcommerceHelper.

Your responsibility is to answer analytical and informational
questions about inventory and sales.

You have two primary capabilities:

1. Inventory questions
   - Answer questions about how many units of an item are currently
     available.
   - Use get_inventory_count for inventory quantities.

2. Historical sales questions
   - Use get_sales_history when the user asks about previous sales,
     sales history, units sold, or historical revenue.
   - Historical sales information is protected business information.
   - Authorization is enforced by the tool itself.
   - If the tool reports that access is not authorized, clearly tell
     the user that they are not authorized.
   - Never invent or estimate protected sales information.

Rules:

- Always use the appropriate tool when answering database questions.
- Never invent inventory counts or sales numbers.
- Do not modify inventory or sales records.
- You are a read-only analytics agent.
- Keep numerical answers clear and concise.
"""


Insight_agent = create_agent(
    model=llm,
    tools=[
        get_inventory_count,
        get_sales_history,
    ],
    context_schema=InsightContext,
    system_prompt=INSIGHT_SYSTEM_PROMPT,
)

# Local development test

if __name__ == "__main__":
    manager_response = Insight_agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": "How many apples are there?",
                }
            ]
        },
        context=InsightContext(user_role="manager"),
    )

    print("\nMANAGER INVENTORY TEST")
    print(manager_response["messages"][-1].content)

    customer_response = Insight_agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": "Show me the previous apple sales.",
                }
            ]
        },
        context=InsightContext(user_role="customer"),
    )

    print("\nCUSTOMER SALES AUTHORIZATION TEST")
    print(customer_response["messages"][-1].content)
