from datetime import date
import os
import sqlite3
import pandas as pd

from typing import TypedDict

from dotenv import load_dotenv
from langchain_core.tools import tool
from langchain.agents import create_agent
from langchain_openai import ChatOpenAI
from langchain.messages import HumanMessage


# =========================================================
# 1. Configuration
# =========================================================

load_dotenv()

DB_NAME = "ecommerce.db"

llm = ChatOpenAI(
    model="gpt-5-nano",
    api_key=os.getenv("OPENAI_API_KEY"),
    temperature=0
)


# =========================================================
# 2. LangGraph State
# =========================================================

class AgentState(TypedDict):
    messages: list
    insert_count: int


# =========================================================
# 3. Database Helper
# =========================================================

def get_sales():

    conn = sqlite3.connect(DB_NAME)

    try:
        df = pd.read_sql_query(
            "SELECT * FROM sales",
            conn
        )

        return df

    finally:
        conn.close()


# =========================================================
# 4. SQL Execution Tool
# =========================================================

@tool
def execute_sql(query: str) -> str:
    """
    Execute exactly one SQL statement against the SQLite database.

    This tool is responsible for executing the SQL generated by
    the sales agent.
    """

    query = query.strip()

    # -----------------------------------------------------
    # Safety check
    # -----------------------------------------------------

    statements = [
        statement.strip()
        for statement in query.split(";")
        if statement.strip()
    ]

    if len(statements) != 1:
        return (
            "SQL BLOCKED: Only one SQL statement is allowed "
            "per sales request."
        )

    sql = statements[0]

    # -----------------------------------------------------
    # Only INSERT into sales is allowed
    # -----------------------------------------------------

    if not sql.upper().startswith("INSERT"):
        return (
            "SQL BLOCKED: Only INSERT statements are allowed "
            "by the sales SQL tool."
        )

    if "SALES" not in sql.upper():
        return (
            "SQL BLOCKED: INSERT must target the sales table."
        )

    conn = sqlite3.connect(DB_NAME)

    try:

        cursor = conn.cursor()

        cursor.execute(sql)

        conn.commit()

        result = (
            "Sales record inserted successfully.\n"
            f"Rows affected: {cursor.rowcount}"
        )

        return result

    except Exception as e:

        conn.rollback()

        return f"SQL execution failed: {e}"

    finally:

        conn.close()


# =========================================================
# 5. Sales SQL Agent
# =========================================================

today = date.today().isoformat()

sales_system_prompt = f"""
You are a SQL generation agent for the Sales system.

Your job is to convert the user's request into ONE valid SQLite
INSERT statement.

Database schema:

sales(
    sale_id INTEGER PRIMARY KEY,
    item TEXT,
    date TEXT,
    count INTEGER,
    total_price REAL
)

Today's date is:

{today}

Rules:

1. Generate exactly ONE SQL statement.

2. The SQL statement must be an INSERT statement.

3. Insert into the sales table.

4. Never generate multiple INSERT statements.

5. Never generate multiple SQL statements.

6. If the user requests one item, generate one sales row.

7. Do not invent columns.

8. Use only columns that exist in the sales table.

9. If a date is not provided, use today's date:
   {today}

10. The total_price must be the total cost supplied by the
    calling agent.

11. Return ONLY the SQL statement.

Example:

User:
Buy 2 apples for $3.00.

Output:

INSERT INTO sales (item, date, count, total_price)
VALUES ('apples', '{today}', 2, 3.00);
"""


sales_agent = create_agent(
    model=llm,
    tools=[],
    system_prompt=sales_system_prompt,
)


# =========================================================
# 6. Calculate Total Cost
# =========================================================

@tool
def calculate_total_cost(count: int, item: str) -> str:
    """
    Calculate the total cost using the item's price from inventory.
    """

    conn = sqlite3.connect(DB_NAME)

    try:

        df = pd.read_sql_query(
            """
            SELECT price_per_item
            FROM lookup_items
            WHERE LOWER(item) = LOWER(?)
            LIMIT 1
            """,
            conn,
            params=(item,)
        )

    finally:

        conn.close()

    # -----------------------------------------------------
    # Prevent iloc[0] error
    # -----------------------------------------------------

    if df.empty:

        return (
            f"Item '{item}' was not found in inventory."
        )

    price_per_item = float(
        df.iloc[0]["price_per_item"]
    )

    total_cost = count * price_per_item

    return (
        f"Item: {item}\n"
        f"Count: {count}\n"
        f"Price per item: ${price_per_item:.2f}\n"
        f"Total cost: ${total_cost:.2f}"
    )


# =========================================================
# 7. Sales Record Tool
# =========================================================

@tool
def sales_record(
    count: int,
    item: str,
    total_cost: float,
    state: AgentState
) -> str:
    """
    Create exactly one sales record.

    The sales database can only be modified once per request.
    """

    # -----------------------------------------------------
    # HARD LIMIT
    # -----------------------------------------------------

    if state["insert_count"] >= 1:

        return (
            "INSERT BLOCKED: "
            "Only one sales insertion is allowed per request."
        )

    # -----------------------------------------------------
    # Generate SQL using the Sales Agent
    # -----------------------------------------------------

    response = sales_agent.invoke(
        {
            "messages": [
                HumanMessage(
                    content=f"""
                    Create one sales INSERT statement.

                    Item: {item}
                    Count: {count}
                    Total cost: {total_cost}
                    """
                )
            ]
        }
    )

    sql_query = response["messages"][-1].content.strip()

    print("\nGenerated SQL:")
    print(sql_query)

    # -----------------------------------------------------
    # Validate that only ONE SQL statement exists
    # -----------------------------------------------------

    statements = [
        statement.strip()
        for statement in sql_query.split(";")
        if statement.strip()
    ]

    if len(statements) != 1:

        return (
            "INSERT BLOCKED: "
            "Sales agent generated more than one SQL statement."
        )

    # -----------------------------------------------------
    # Execute exactly ONE INSERT
    # -----------------------------------------------------

    result = execute_sql.invoke(
        {
            "query": sql_query
        }
    )

    # -----------------------------------------------------
    # Update state ONLY after successful insertion
    # -----------------------------------------------------

    if "successfully" in result.lower():

        state["insert_count"] = 1

        return (
            f"{result}\n"
            f"Insert count: {state['insert_count']}"
        )

    return result


# =========================================================
# 8. External Sales Agent
# =========================================================

external_system_prompt = """
You are the Sales Assistant.

Your job is to process a customer purchase request.

Workflow:

1. Extract the item and quantity.
2. Call calculate_total_cost.
3. If the item does not exist, stop and report the problem.
4. If total cost is known, call sales_record exactly once.
5. Do not call sales_record again after it succeeds.
6. Do not attempt multiple sales insertions.
7. Return the final result to the user.
"""


Ext_agent = create_agent(
    model=llm,
    tools=[
        calculate_total_cost,
        sales_record
    ],
    system_prompt=external_system_prompt,
)


# =========================================================
# 9. Run Agent
# =========================================================

initial_state = {
    "messages": [],
    "insert_count": 0
}


# question = HumanMessage(
#     content="I want to buy 3 apple."
# )


# response = Ext_agent.invoke(
#     {
#         "messages": [question],
#         "insert_count": 0
#     }
# )


# print("\nFinal Response:")
# print(response["messages"][-1].content)